// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjhsvrksrmcemhbglfkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qaHN2cmtzcm1jZW1oYmdsZmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTEyNjUsImV4cCI6MjA2NjU2NzI2NX0.olEu3Nox_GdD5kzoXItRJy_v-gm6laW1C8hPt_B7MvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});